version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/server/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/client/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
